elevation_mapping:
  ros__parameters:
    inputs: ['ground_truth_cloud1', 'ground_truth_cloud2']
    ground_truth_cloud1: # A name to identify the input source
      type: pointcloud # Supported types: pointcloud
      topic: /left_laser/pandar
      queue_size: 1
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
        type: laser
        min_radius: 1.5
        ignore_points_above: 0.8
    ground_truth_cloud2: # A name to identify the input source
      type: pointcloud # Supported types: pointcloud
      topic: /right_laser/pandar
      queue_size: 1
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
        type: laser
        min_radius: 1.5
        ignore_points_above: 0.8
    map_frame_id: "map"
    robot_base_frame_id: "base_footprint"
    robot_pose_with_covariance_topic: "ukf_pose"
    robot_pose_cache_size: 200
    min_update_rate: 0.5
    track_point_frame_id: "base_footprint"
    # robot_pose_topic:  "ukf_pose"
    #track_point_x: 0.0
    #track_point_y: 0.0
    #track_point_z: 0.0
